name: mlexps
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.7
  - jupyter
  - jupyter_contrib_nbextensions
  - pip:
    - --index-url=https://pypi.org/simple
    - --trusted-host=[pypi.org]
    - -rrequirements.txt
